#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_
#include "user_monitor.h"
typedef enum
{
	LANGUAGE_ID_ENGLISH = 0,
	// LANGUAGE_ID_HANYU,
	// LANGUAGE_ID_ELUOSI,
	// LANGUAGE_ID_XIBANYA,
	// LANGUAGE_ID_CHINESE,
	// LANGUAGE_ID_TUERQI,
	// LANGUAGE_ID_BOLAN,
	// LANGUAGE_ID_JIEKE,
	LANGUAGE_ID_ALABOYU,
	// LANGUAGE_ID_PUTAOYA,
	// LANGUAGE_ID_FAYU,
	// LANGUAGE_ID_DEYU,

	LANGUAGE_ID_TOTAL
} LANGUAGE_ID;

/***
** 日期: 2022-04-26 08:55
** 作者: leo.liu
** 函数作用：设置当前语言
** 返回参数说明：
***/
void language_id_set(LANGUAGE_ID id);

/***
** 日期: 2022-04-26 08:56
** 作者: leo.liu
** 函数作用：获取当前语言ID
** 返回参数说明：
***/
LANGUAGE_ID language_id_get(void);

typedef enum
{
	HOME_LANG_ID_MONITOR = 0,
	HOME_LANG_ID_CCTV,
	HOME_LNAG_ID_INTER,
	HOME_LANG_ID_PLAYBACK,
	HOME_LANG_ID_SECURITY,
	HOME_LANG_ID_WEEK_1,
	HOME_LANG_ID_WEEK_2,
	HOME_LANG_ID_WEEK_3,
	HOME_LANG_ID_WEEK_4,
	HOME_LANG_ID_WEEK_5,
	HOME_LANG_ID_WEEK_6,
	HOME_LANG_ID_WEEK_7,

	HOME_LANG_ID_MONTH_1,
	HOME_LANG_ID_MONTH_2,
	HOME_LANG_ID_MONTH_3,
	HOME_LANG_ID_MONTH_4,
	HOME_LANG_ID_MONTH_5,
	HOME_LANG_ID_MONTH_6,
	HOME_LANG_ID_MONTH_7,
	HOME_LANG_ID_MONTH_8,
	HOME_LANG_ID_MONTH_9,
	HOME_LANG_ID_MONTH_10,
	HOME_LANG_ID_MONTH_11,
	HOME_LANG_ID_MONTH_12,

	HOME_LANG_ID_TUYA_PREVIEW,
	HOME_LANG_ID_TUYA_TALK,

	HOME_LANG_ID_AT_HOME,
	HOME_LANG_ID_LEAVE_HOME,
	HOME_LANG_ID_DORMANCY_HOME,
	HOME_LANG_ID_CCTV_LEBAL,
	HOME_LANG_ID_DOOR_LEBAL,

	HOME_LANG_ID_TOTAL
} LAYOUT_HOME_LANG_ID;






/***
** 日期: 2022-04-26 09:16
** 作者: leo.liu
** 函数作用：获取home页面的字符串资源
** 返回参数说明：
***/
const char *layout_home_string_get(LAYOUT_HOME_LANG_ID id);

typedef enum
{
	SETTING_RECORD_LANG_ID_SETTING = 0,
	SETTING_RECORD_LANG_ID_RECORD_WIFI,
	SETTING_RECORD_LANG_ID_VOLUME,
	SETTING_RECORD_LANG_ID_STORAGE,
	SETTING_RECORD_LANG_ID_DATE,
	SETTING_RECORD_LANG_ID_DISPLAY,
	SETTING_RECORD_LANG_ID_ETC,

	SETTING_RECORD_LANG_ID_AUTO_RECORD,
	SETTING_RECORD_LANG_ID_MOTION_DETECTION,
	SETTING_RECORD_LANG_ID_WIFI,
	SETTING_RECORD_LANG_ID_ALWAYS,

	SETTING_RECORD_LANG_ID_ALWAYS_10SEC,
	SETTING_RECORD_LANG_ID_ALWAYS_30SEC,
	SETTING_RECORD_LANG_ID_ALWAYS_60SEC,

	SETTING_RECORD_LANG_ID_DOOR1_ALWAYS,
	SETTING_RECORD_LANG_ID_DOOR2_ALWAYS,
	SETTING_VOLUME_LANG_ID_DOOR1,
	SETTING_VOLUME_LANG_ID_DOOR2,
	SETTING_VOLUME_LANG_ID_INTERCOM,
	SETTING_VOLUME_LANG_ID_API_YANZHONG,
	SETTING_VOLUME_LANG_ID_API_QINGDU,
	SETTING_VOLUME_LANG_ID_API_YIBAN,
	SETTING_VOLUME_LANG_ID_API_YOUZHI,


	SETTING_VOLUME_LANG_ID_API_LISE_OF_DISPLAY,
	SETTING_VOLUME_LANG_ID_API_DIGITAL_FRAME_TIME,
	SETTING_VOLUME_LANG_ID_API_OPEN_FRAME_TIME,
	SETTING_VOLUME_LANG_ID_API_NIGHT,

	SETTING_RECROD_LANG_ID_TOTAL
} LAYOUT_SETTING_RECORD_LANG_ID;



/***
** 日期: 2022-04-28 10:48
** 作者: leo.liu
** 函数作用：获取setting recrod页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_record_string_get(LAYOUT_SETTING_RECORD_LANG_ID id);


typedef enum 
{
    HOME_WEATHER_LANG_ID_DAYU,
    HOME_WEATHER_LANG_ID_LEIBAO,
    HOME_WEATHER_LANG_ID_SHACHENBAO,
    HOME_WEATHER_LANG_ID_XIAOXUE,
    HOME_WEATHER_LANG_ID_XUE,
    HOME_WEATHER_LANG_ID_DONGWU,
    HOME_WEATHER_LANG_ID_BAOYU,
    HOME_WEATHER_LANG_ID_JUBUZHENYU,
    HOME_WEATHER_LANG_ID_FUCHEN,
    HOME_WEATHER_LANG_ID_LEIDINA,
    HOME_WEATHER_LANG_ID_XIAOZHENYU,
    HOME_WEATHER_LANG_ID_YU,
    HOME_WEATHER_LANG_ID_YUJIAXUE,
    HOME_WEATHER_LANG_ID_CHENJUANFENG,
    HOME_WEATHER_LANG_ID_BINGLI,
    HOME_WEATHER_LANG_ID_QIANGSHAHCENBAO,
    HOME_WEATHER_LANG_ID_YANGSHA,
    HOME_WEATHER_LANG_ID_XIAODAOZHONGYU,
    HOME_WEATHER_LANG_ID_DABUQINGLANG,
    HOME_WEATHER_LANG_ID_QING,
    HOME_WEATHER_LANG_ID_WU,
    HOME_WEATHER_LANG_ID_ZHENYU,
    HOME_WEATHER_LANG_ID_QIANGZHENYU,
    HOME_WEATHER_LANG_ID_DAXUE,
    HOME_WEATHER_LANG_ID_TEDABAOYU,
    HOME_WEATHER_LANG_ID_BAOXUE,
    HOME_WEATHER_LANG_ID_BINGBAO,
    HOME_WEATHER_LANG_ID_XIAODAOZHONGXUE,
    HOME_WEATHER_LANG_ID_SHAOYUN,
    HOME_WEATHER_LANG_ID_XIAOZHENXUE,
    HOME_WEATHER_LANG_ID_ZHONGXUE,
    HOME_WEATHER_LANG_ID_YIN,
    HOME_WEATHER_LANG_ID_BINGZHEN,
    HOME_WEATHER_LANG_ID_DABAOYU,
	HOME_WEATHER_LANG_ID_WUDINGYI,
    HOME_WEATHER_LANG_ID_LEIZHENYUBANYOUBINGBAO,
    HOME_WEATHER_LANG_ID_DONGYU,
    HOME_WEATHER_LANG_ID_ZHENXUE,
    HOME_WEATHER_LANG_ID_XIAOYU,
    HOME_WEATHER_LANG_ID_MAI,
    HOME_WEATHER_LANG_ID_ZHONGYU,
    HOME_WEATHER_LANG_ID_DUOYUN,
    HOME_WEATHER_LANG_ID_LEIZHENYU,
    HOME_WEATHER_LANG_ID_ZHONGDAODAYU,
    HOME_WEATHER_LANG_ID_DADAOBAOYU,
    HOME_WEATHER_LANG_ID_QINGLANG,
    HOME_WEATHER_LANG_ID_TOTAL
} LAYOUT_HOME_WEATHER_LANG_ID;

const char *layout_home_weather_string_get(LAYOUT_HOME_WEATHER_LANG_ID id);

typedef enum
{
	HOME_WEATHER_LABEL_LANG_ID_HUMIDITY,
	HOME_WEAHER_LABEL_LANG_ID_PRESSURE,
	HOME_WEATHERLABEL_LANG_ID_PM10,
	HOME_WEATHER_LABEL_LANG_ID_PM25,
	HOME_WEATHER_LABEL_LANG_ID_P,
	HOME_WEATHER_LABEL_LANG_ID_TOTAL
}LAYOUT_HOME_WEATHER_MILIEU_LANG_ID;

const char *layout_home_weather_milieu_string_get(LAYOUT_HOME_WEATHER_MILIEU_LANG_ID id);

typedef enum
{
	LANG_COMMON_ID_OFF = 0,
	LANG_COMMON_ID_ON,
	LANG_COMMON_ID_VIDEO,
	LANG_COMMON_ID_PHOTO,
	LANG_COMMON_ID_CANCEL,
	LANG_COMMON_ID_CONFIRM,
	LANG_COMMON_ID_DOOR1,
	LANG_COMMON_ID_DOOR2,
	LANG_COMMON_ID_CCTV1,
	LANG_COMMON_ID_CCTV2,
	LANG_COMMON_ID_CCTV3,
	LANG_COMMON_ID_CCTV4,

	LANG_COMMON_ID_TUYA_SAVE,

	LANG_COMMON_ID_TOTAL
} LANG_COMMON_ID;

/***
** 日期: 2022-04-28 13:55
** 作者: leo.liu
** 函数作用：获取公共字符串的字符串资源
** 返回参数说明：
***/
const char *language_common_string_get(LANG_COMMON_ID id);

/***
**   日期:2022-05-24 10:04:38
**   作者: leo.liu
**   函数作用：根据通道类型获取字符串
**   参数说明:
***/
const char *language_common_ch_string_get(MON_CH ch);

typedef enum
{
	/***** volume 在record中已经有了 *****/
	SETTING_VOLUME_LANG_ID_TOUCH_TONE,
	SETTING_VOLUME_LANG_ID_DOOR1_TONE,
	SETTING_VOLUME_LANG_ID_DOOR2_TONE,
	SETTING_VOLUME_LANG_ID_DOOR_TONE,
	SETTING_VOLUME_LANG_ID_INTERPHONE_TONE,

	SETTING_VOLUME_LANG_ID_TONE1,
	SETTING_VOLUME_LANG_ID_TONE2,
	SETTING_VOLUME_LANG_ID_TONE3,
	SETTING_VOLUME_LANG_ID_TONE4,
	SETTING_VOLUME_LANG_ID_TONE5,
	SETTING_VOLUME_LANG_ID_TONE6,
	SETTING_VOLUME_LANG_ID_TOTAL
} LAYOUT_SETTING_VOLUME_LANG_ID;

/***
** 日期: 2022-04-29 08:14
** 作者: leo.liu
** 函数作用：获取setting volume 页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_volume_string_get(LAYOUT_SETTING_VOLUME_LANG_ID);

typedef enum
{
	/***** volume 在record中已经有了 *****/
    RING_RING1,
    RING_RING2,
    RING_RING3,
    RING_SCHEDULE,
    RING_TIME,
    RING_MODE,
    RING_MODE_STD,
    RING_MODE_CUSTOM,
    RING_SELECT,
    RING_VOLUME,
	COMMON_NO_SD,
	COMMON_SD_INSERTED,

	COMMON_CANCEL,
	COMMON_OK,
	COMMON_ERROR,

	SETTING_RING_LANG_ID_TOTAL
} LAYOUT_SETTING_RING_LANG_ID;

/***
** 日期: 2022-04-29 08:14
** 作者: leo.liu
** 函数作用：获取setting volume 页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_ring_string_get(LAYOUT_SETTING_RING_LANG_ID);


typedef enum
{

	SETTING_STORAGE_LANG_ID_FORMAT_SD,
	SETTING_STORAGE_LANG_ID_DELETION_FILE,
	SETTING_STORAGE_LANG_ID_MSG_FORMAT_SD,
	SETTING_STORAGE_LANG_ID_MSG_DEL_FILE,
	SETTING_STORAGE_LANG_ID_SD,
	SETTING_STORAGE_LANG_ID_FLASH,
	SETTING_STORAGE_LANG_ID_FLASH_PHOTO_TO_SD,
	SETTING_STORAGE_LANG_ID_TOTAL

} LAYOUT_SETTING_STORAGE_LANG_ID;

/***
** 日期: 2022-04-29 15:33
** 作者: leo.liu
** 函数作用：获取setting storage 页面的字符串资源
** 返回参数说明：
***/


const char *layout_setting_storage_string_get(LAYOUT_SETTING_STORAGE_LANG_ID id);

typedef enum
{
	SETTING_DATE_LANG_ID_SYS_TIME,
	SETTING_DATE_LANG_ID_TOTAL
} LAYOUT_SETTING_DATE_LANG_id;

/***
** 日期: 2022-05-04 09:52
** 作者: leo.liu
** 函数作用：获取setting date/time 页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_systime_string_get(LAYOUT_SETTING_DATE_LANG_id id);

typedef enum
{
	SETTING_DISPLAY_LANG_ID_SCREEN_ADJ,
	SETTING_DISPLAY_LANG_ID_STANDBY_MODE,
	SETTING_DISPLAY_LANG_ID_DISPLAY_CLEAN,
	SETTING_DISPLAY_LANG_ID_DISPLAY_BRIGHTNESS,

	SETTING_DISPLAY_LANG_ID_LCD_OFF,
	SETTING_DISPLAY_LANG_ID_OPEN_FRAME,

	SETTING_DISPLAY_LANG_ID_FINISH_TIME,

	SETTING_DISPLAY_LANG_ID_TOTAL
} LAYOUT_SETTING_DISPLAY_LANG_ID;

/***
** 日期: 2022-05-04 10:00
** 作者: leo.liu
** 函数作用：获取setting disply 页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_display_string_get(LAYOUT_SETTING_DISPLAY_LANG_ID id);

typedef enum
{
	SETTING_ETC_LANG_ID_LANGUAGE,
	SETTING_ETC_LANG_ID_OPEN_THE_DOOR,
	SETTING_ETC_LANG_ID_SET_ID,
	SETTING_ETC_LANG_ID_DOOR1_OPEN_MODULE,
	SETTING_ETC_LANG_ID_SECURITY_PASSWORD,
	SETTING_ETC_LANG_ID_SYSTEM_RESET,
	SETTING_ETC_LANG_ID_WEATHER,
	SETTING_ETC_LANG_ID_SECURITY,
	SETTING_ETC_LANG_ID_CCTV_MANAGE,
	SETTING_ETC_LANG_ID_VERSION,
	SETTING_ETC_LANG_ID_NUM_DOOR2_OPEN,

	SETTING_ETC_LANG_ID_LANGUAGE_SUB,
	SETTING_ETC_LANG_ID_FAST_MODE,
	SETTING_ETC_LANG_ID_STANDBY_MODE,
	SETTING_ETC_LANG_ID_DOOR_CAMERA,
	SETTING_ETC_LANG_ID_DIGITAL_DOOR_LOCK,

	SETTING_ETC_LANG_ID_DEVICE_ID1,
	SETTING_ETC_LANG_ID_DEVICE_ID2,
	SETTING_ETC_LANG_ID_DEVICE_ID3,
	SETTING_ETC_LANG_ID_DEVICE_ID4,

	SETTING_ETC_LANG_ID_SYSTIME_RESET_SUB,

	SETTING_ETC_LANG_ID_DOOR2_NUM_1,
	SETTING_ETC_LANG_ID_DOOR2_NUM_2,
	SETTING_ETC_LANG_ID_DOOR_1_OPEN_TIME,
	SETTING_ETC_LANG_ID_DOOR_2_OPEN_TIME,
	SETTING_ETC_LANG_ID_TUYA_SEND_TIME,
	SETTING_ETC_LANG_ID_TUYA_UUID,
	SETTING_ETC_LANG_ID_TUYA_SWITCH,

	SETTING_ETC_LANG_ID_ADDED_DEV,
	SETTING_ETC_LANG_ID_DISCOVERED_DEV,
	SETTING_ETC_LANG_ID_SEARCH_DEV,
	SETTING_ETC_LANG_ID_REGISTER_DEV,
	SETTING_ETC_LANG_ID_BRAND,
	SETTING_ETC_LANG_ID_IP_ADDRESS,
	SETTING_ETC_LANG_ID_ACCOUNT,
	SETTING_ETC_LANG_ID_PASSWORD,
	SETTING_ETC_LANG_ID_MAIN_STREAM,
	SETTING_ETC_LANG_ID_SUB_STREAM,
	SETTING_ETC_LANG_ID_DEL_DEV,

	SETTING_ETC_LANG_ID_BRAND_PAN,
	SETTING_ETC_LANG_ID_BRAND_DAHUA,
	SETTING_ETC_LANG_ID_BRAND_HIKVISION,
	SETTING_ETC_LANG_ID_BRAND_XM,
	SETTING_ETC_LANG_ID_BRAND_RTSP,


	SETTING_ETC_LANG_ID_INPUT_IP_ADDR,
	SETTING_ETC_LANG_ID_INPUT_ACCOUNT,
	SETTING_ETC_LANG_ID_INPUT_PASSWORD,
	SETTING_ETC_LANG_ID_INPUT_RTSP,
	SETTING_ETC_LANG_ID_TP_CHECK,

	SETTING_ETC_LANG_ID_TOTAL
} LAYOUT_SETTING_ETC_LANG_ID;

/***
** 日期: 2022-05-04 13:59
** 作者: leo.liu
** 函数作用：获取setting etc display 页面的字符串资源
** 返回参数说明：
***/
const char *layout_setting_etc_string_get(LAYOUT_SETTING_ETC_LANG_ID id);

/***
** 日期: 2022-05-07 10:20
** 作者: leo.liu
** 函数作用：获取指定的语言
** 返回参数说明：
***/
const char *layout_setting_etc_string_get_form_language(LAYOUT_SETTING_ETC_LANG_ID string_id, LANGUAGE_ID language_id);

typedef enum
{
	SETTING_MOTION_LANG_ID_USE_MOTION_DETECT,
	SETTING_MOTION_LANG_ID_SELECT_CAMERA,
	SETTING_MOTION_LANG_ID_SAVING_FORMAT,
	SETTING_MOTION_LANG_ID_MOTION_HIGHT,
	SETTING_MOTION_LANG_ID_MOTION_MIDDLE,
	SETTING_MOTION_LANG_ID_MOTION_LOW,
	SETTING_MOTION_LANG_ID_SENSITIVITY,
	SETTING_MOTION_LANG_ID_MOTION_TIMER,
	SETTING_MOTION_LANG_ID_LCD_IS_ON,
	SETTING_MOTION_LANG_ID_USE_TIMER,
	SETTING_MOTION_LANG_ID_TOTAL
} LAYOUT_SETTING_MOTION_LANG_ID;
/***
** 日期: 2022-05-05 11:40
** 作者: leo.liu
** 函数作用：移动侦测设置资源获取
** 返回参数说明：
***/
const char *layout_setting_motion_string_get(LAYOUT_SETTING_MOTION_LANG_ID id);

typedef enum
{
	SETTING_FRAME_LANG_ID_OPEN_FRAME_TIME = 0,
	SETTING_FRAME_LANG_ID_NIGHT_MODE,
	SETTING_FRAME_LANG_ID_LIST_OF_DISPLAY,
	SETTING_FRAME_LANG_ID_IMAGE_OF_BACKGROUND,

	SETTING_FRAME_LANG_ID_ALWAYS,
	SETTING_FRAME_LANG_ID_NO_BACKGROUND_IMAGE,
	SETTING_FRAME_LANG_ID_BASIC_IMAGE,

	SETTING_FRAME_LANG_ID_NOT_AVAILABLE,

	SETTING_FRAME_LANG_ID_TIME_SET,
	SETTING_FRAME_LANG_ID_START,
	SETTING_FRAME_LANG_ID_END,

	SETTING_FRAME_LANG_ID_TIME,
	SETTING_FRAME_LANG_ID_CALENDAR,
	SETTING_FRAME_LANG_ID_PLAYBACK,
	SETTING_FRAME_LANG_ID_DOOR1_CCTV1,
	SETTING_FRAME_LANG_ID_DOOR2_CCTV2,
	SETTING_FRAME_LANG_ID_SD_IMAGE,
	SETTING_FRAME_LANG_ID_TOTAL
} LAYOUT_SETTING_FRAME_LANG_ID;
/***
** 日期: 2022-05-06 15:26
** 作者: leo.liu
** 函数作用：待机设置资源获取
** 返回参数说明：
***/
const char *layout_setting_frame_string_get(LAYOUT_SETTING_FRAME_LANG_ID id);

typedef enum
{
	SETTING_PASSWORD_LANG_ID_PWD_NOT_MATCH,
	SETTING_PASSWORD_LANG_ID_APPLE,
	SETTING_PASSWORD_LANG_ID_ENTER_PWD,
	SETTING_PASSWORD_LANG_ID_PWD_RESET,
	SETTING_PASSWORD_LANG_ID_NEW_PWD,
	SETTING_PASSWORD_LANG_ID_CONFIRM_PWD,
	SETTING_PASSWORD_LANG_ID_TOTAL
} LAYOUT_SETTING_PASSWORD_LANG_ID;

/***
** 日期: 2022-05-07 15:55
** 作者: leo.liu
** 函数作用：密码相关字符串资源
** 返回参数说明：
***/
const char *layout_setting_password_string_get(LAYOUT_SETTING_PASSWORD_LANG_ID id);

typedef enum
{
	PLAYBACK_LANG_ID_DELETE_PHOTO,
	PLAYBACK_LANG_ID_DELETE_VIDEO,
	PLAYBACK_LANG_ID_TOTAL
} LAYOUT_PLAYBACK_LANGUAGE_ID;
/***
**   日期:2022-05-24 11:17:49
**   作者: leo.liu
**   函数作用：playback
**   参数说明:
***/
const char *layout_playback_string_get(LAYOUT_PLAYBACK_LANGUAGE_ID id);

typedef enum
{
	LAYOUT_SECURITY_LANGUAGE_ID_AUTO_REC,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_2,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_WORKING,
	LAYOUT_SECURITY_LANGUAGE_ID_END,
	LAYOUT_SECURITY_LANGUAGE_ID_EXE,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1_ERROR,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_2_ERROR,
	LAYOUT_SECURITY_LANGUAGE_ID_SENSOR_1_AND_2_ERROR,

	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY_EMERGENCY,
	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY_EMERGENCY_1,
	LAYOUT_SECURITY_LANGUAGE_ID_SECURITY_EMERGENCY_2,

	LAYOUT_SECURITY_LANGUAGE_ID_EMERITY_RECORD,
	LAYOUT_SECURITY_LANGUAGE_ID_TOTAL
} LAYOUT_SECURITY_LANGUAGE_ID;
/***
**   日期:2022-05-26 14:39:55
**   作者: leo.liu
**   函数作用：安全警报字符资源
**   参数说明:
***/
const char *layout_security_string_get(LAYOUT_SECURITY_LANGUAGE_ID id);

typedef enum
{
	LAYOUT_INTERCOM_LANGUAGE_ID_CALLING,
	LAYOUT_INTERCOM_LANGUAGE_ID_TALKING,
	LAYOUT_INTERCOM_LANGUAGE_ID_PROMPT,
	LAYOUT_INTERCOM_LANGUAGE_ID_TISHI,
	LAYOUT_INTERCOM_LANGUAGE_ID_TOTAL,
} LAYOUT_INTERCOM_LANGUAGE_ID;
/***
**   日期:2022-05-30 09:17:03
**   作者: leo.liu
**   函数作用：intercom页面
**   参数说明:
***/
const char *layout_intercom_string_get(LAYOUT_INTERCOM_LANGUAGE_ID id);


typedef enum
{
	LAYOUT_WIFI_LANGUAGE_ID_WIFI,
	LAYOUT_WIFI_LANGUAGE_ID_NETWORK_CONNECTED,
	LAYOUT_WIFI_LANGUAGE_ID_SEARCHED_NETWORK,
	LAYOUT_WIFI_LANGUAGE_ID_WIFI_SECURITY,
	LAYOUT_WIFI_LANGUAGE_ID_IP_ADDRES,
	LAYOUT_WIFI_LANGUAGE_ID_ADD_WIFI,
	LAYOUT_WIFI_LANGUAGE_ID_ENTER_ACCOUNT,
	LAYOUT_WIFI_LANGUAGE_ID_WIFI_CONNECTING,
	LAYOUT_WIFI_LANGUAGE_ID_NTWORK_ERROR,

	LAYOUT_WIFI_LANGUAGE_ID_NAME_EMPTY,
	LAYOUT_WIFI_LANGUAGE_ID_NAME_SHORT,
	LAYOUT_WIFI_LANGUAGE_ID_PWD_SHORT,
	LAYOUT_WIFI_LANGUAGE_ID_PWD_LONG,
	LAYOUT_WIFI_LANGUAGE_ID_PWD_ERROR,
	LAYOUT_WIFI_LANGUAGE_ID_PWD_IGNORE,


	LAYOUT_WIFI_LANGUAGE_ID_TOTAL
} LAYOUT_WIFI_LANGUAGE_ID;
/***
**   日期:2022-06-06 08:35:34
**   作者: leo.liu
**   函数作用：wifi所需资源
**   参数说明:
***/
const char *layout_wifi_string_get(LAYOUT_WIFI_LANGUAGE_ID id);
#endif