cmd_crypto/jitterentropy.o := /home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/tools/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc -Wp,-MD,crypto/.jitterentropy.o.d  -nostdinc -isystem /home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/tools/arm-anykav500-linux-uclibcgnueabi/bin/../lib/gcc/arm-anykav500-linux-uclibcgnueabi/4.9.4/include -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/include -Iinclude -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/include/uapi -Iinclude/generated/uapi -include /home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/include/linux/kconfig.h  -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/crypto -Icrypto -D__KERNEL__ -mlittle-endian   -I/home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/arch/arm/mach-anycloud/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -marm -D__LINUX_ARM_ARCH__=5 -march=armv5te -mtune=arm9tdmi -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=4096 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -O0    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(jitterentropy)"  -D"KBUILD_MODNAME=KBUILD_STR(jitterentropy_rng)" -c -o crypto/jitterentropy.o /home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/crypto/jitterentropy.c

source_crypto/jitterentropy.o := /home/xiaoxiao/workspace/meiou/meiou_AK37D_fenqu/os/kernel/crypto/jitterentropy.c

deps_crypto/jitterentropy.o := \
    $(wildcard include/config/x86/tsc.h) \

crypto/jitterentropy.o: $(deps_crypto/jitterentropy.o)

$(deps_crypto/jitterentropy.o):
